# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f620438cf13989a38c1ad32aeb102f429fb8b9300f3ef46f13e251f50caeff75f58ccdc7dbe4b0ff560ef6836a74daffe956c4ece50a12285b350d5c082e0e11

test:
  secret_key_base: cdf62645ae8f03e4461d71e36da422e024e969e59a71838806a975a2bc90112a34a988fc5cb8afe022034abd0bf670455f2f68f19ab9835b2d1eebc63ed97825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
